module.exports = {
  apps: [
    {
      name: 'animl-base',
      script: './src/app.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      exp_backoff_restart_delay: 100,
      time: true,
      shutdown_with_message: true,
      kill_timeout: 5000,
    },
    {
      name: 'disk-management',
      script: './cron/disk.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '* */1 * * *',
      watch: false,
      autorestart: false,
    },
    {
      name: 'watchdog',
      script: './cron/watchdog.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '* 1 * * *',
      watch: false,
      autorestart: false,
    },
    // {
    //   name: 'temperature-logger',
    //   script: 'python temp-monitor.py',
    //   instances: 1,
    //   autorestart: true,
    //   exp_backoff_restart_delay: 100,
    //   watch: false,
    // },
  ],
};
